package com.stackroute.model;

import javax.persistence.*;
import java.time.LocalDate;

/*
Add appropriate annotation/s to map the class and its properties with a Database entity
    - employeeId should be unique and generated by the Database
    - table name should be employees_store
*/

@Entity
@Table()
public class Employee {
    private Integer employeeId;
    private String sectorId;
    private String branchId;
    private LocalDate employeeJoiningDate;
    private String departmentName;
    private double salary;

    // Define a no argument constructor

    // Define All argument constructor

    // Define Getter and Setter for all Employee field
}